.TH "srclib Directory Reference" 3 "Sun May 7 2017" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srclib Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBG-2361-06-P1-Daemon\&.c\fP"
.br
.ti -1c
.RI "file \fBG-2361-06-P1-Functions\&.c\fP"
.br
.ti -1c
.RI "file \fBG-2361-06-P1-Server\&.c\fP"
.br
.RI "\fIImplementacion de las funciones del Servidor\&. \fP"
.ti -1c
.RI "file \fBG-2361-06-P1-Sockets\&.c\fP"
.br
.in -1c
