.TH "funcion_ping" 3 "Sun May 7 2017" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
funcion_ping \- funcionPing 
Realiza toda la funcionalidad correspondiente con el comando ping\&.
.PP
.PP
.nf
#include <redes2/irc\&.h>
.fi
.PP
.PP
Esta funcion se encarga de cuando se realiza el comando ping, devuelva un pong\&. Este mensaje se mostraria cada 30 segundos\&.
.PP
\fBParameters:\fP
.RS 4
\fIserver1\fP Servidor 1\&. 
.br
\fIserver2\fP servidor 2\&. 
.br
\fIIDsocket\fP el numero del identificador del socket\&.
.RE
.PP
\fBReturns:\fP
.RS 4
No devuelve nada
.RE
.PP
\fBAuthor:\fP
.RS 4
Celia Mateos de Miguel (cel.mateos@estudiante.uam.es) Beatriz de Pablo Garcia (beatriz.depablo@estudiante.uam.es) Alfonso Sebares Mecha (alfonso.sebares@estudiante.uam.es)
.RE
.PP
\fBDate:\fP
.RS 4
13 de febrero de 2017
.RE
.PP
.PP
 
