.TH "libera_lista" 3 "Sun May 7 2017" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libera_lista \- liberaLista 
Libera la memoria de una lista\&.
.PP
.PP
.nf
#include <redes2/irc\&.h>
.fi
.PP
.PP
Libera una lista que ha sido reservada\&.
.PP
\fBParameters:\fP
.RS 4
\fIlista\fP lista que se quiere liberar\&. 
.br
\fInElems\fP numero de elementos que componen la lista\&.
.RE
.PP
\fBReturns:\fP
.RS 4
No devuelve nada
.RE
.PP
\fBAuthor:\fP
.RS 4
Celia Mateos de Miguel (cel.mateos@estudiante.uam.es) Beatriz de Pablo Garcia (beatriz.depablo@estudiante.uam.es) Alfonso Sebares Mecha (alfonso.sebares@estudiante.uam.es)
.RE
.PP
\fBDate:\fP
.RS 4
13 de febrero de 2017
.RE
.PP
.PP
 
