.TH "srclib Directory Reference" 3 "Mon May 8 2017" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srclib Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBaux_functions\&.c\fP"
.br
.RI "\fIImplementacion de las funciones auxiliares de xchat2\&. \fP"
.ti -1c
.RI "file \fBconexion_tcp\&.c\fP"
.br
.RI "\fIImplementacion de la liberia para conexiones TCP\&. \fP"
.ti -1c
.RI "file \fBlogger\&.c\fP"
.br
.RI "\fIDescripcion de la liberia de log de errores complementaria a /var/log/syslog\&. \fP"
.ti -1c
.RI "file \fBuser_commands\&.c\fP"
.br
.RI "\fIImplementacion de las funciones IRC de usuario de xchat2\&. \fP"
.in -1c
