.TH "src/conexion_tcp_test.c" 3 "Mon May 8 2017" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/conexion_tcp_test.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./includes/conexion_tcp\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char *argv[])"

.PP
.nf
14                                  {
15 
16         /* pruebas en el momento durante el desarrollo, nada persistente*/
17         return EXIT_SUCCESS;
18 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
