.TH "File_args" 3 "Mon May 8 2017" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
File_args \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <aux_functions\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBhostname\fP"
.br
.ti -1c
.RI "char * \fBfilename\fP"
.br
.ti -1c
.RI "int \fBport\fP"
.br
.ti -1c
.RI "long unsigned int \fBlength\fP"
.br
.ti -1c
.RI "char * \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Estructura util para el envio de ficheros 
.SH "Member Data Documentation"
.PP 
.SS "char* File_args::data"

.SS "char* File_args::filename"

.SS "char* File_args::hostname"

.SS "long unsigned int File_args::length"

.SS "int File_args::port"


.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
