.TH "puhelp" 3 "Mon May 8 2017" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
puhelp \- puhelp 
Comando IRC de usuario: HELP
.PP
.PP
.nf
#include "user_commands\&.h"

int puhelp(char* command);
.fi
.PP
.PP
\fBParameters:\fP
.RS 4
\fIcommand\fP Cadena que contiene el comando de usuario correspondiente
.RE
.PP
\fBReturns:\fP
.RS 4
int OK si se ha enviado correctamente el mensaje o ERR si se ha producido un error
.RE
.PP
\fBAuthor:\fP
.RS 4
Celia Mateos de Miguel (cel.mateos@estudiante.uam.es) Beatriz de Pablo Garcia (beatriz.depablo@estudiante.uam.es) Alfonso Sebares Mecha (alfonso.sebares@estudiante.uam.es)
.RE
.PP
\fBDate:\fP
.RS 4
13 de febrero de 2017
.RE
.PP
.PP
 
