.TH "snap_time" 3 "Mon May 8 2017" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
snap_time \- snapTime 
Devuelve una cadena con una snapshot de tiempo en formato H:M:S
.PP
.PP
.nf
#include "types\&.h"

char* snapTime(char* buf, int len);
.fi
.PP
.PP
\fBParameters:\fP
.RS 4
\fIbuf\fP buffer donde escrbir la snap 
.br
\fIlen\fP tamaño del buffer
.RE
.PP
\fBReturns:\fP
.RS 4
char* buffer con la snap de tiempo grabada
.RE
.PP
\fBAuthor:\fP
.RS 4
Alfonso Sebares Mecha (alfonso.sebares@estudiante.uam.es)
.RE
.PP
\fBDate:\fP
.RS 4
13 de febrero de 2017
.RE
.PP
.PP
 
