.TH "includes/types.h" 3 "Mon May 8 2017" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/types.h \- 
.PP
Definicion de tipos e includes comunes utilizados por los distintos modulos\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBERR\fP   -1"
.br
.ti -1c
.RI "#define \fBOK\fP   0"
.br
.ti -1c
.RI "#define \fBMAXDATA\fP   1024"
.br
.ti -1c
.RI "#define \fBMAX_IRC_COMMAND\fP   1000 /*https://www\&.alien\&.net\&.au/irc/irc2numerics\&.html*/"
.br
.ti -1c
.RI "#define \fBRED\fP   '\\x1B[31m'"
.br
.ti -1c
.RI "#define \fBGRN\fP   '\\x1B[32m'"
.br
.ti -1c
.RI "#define \fBYEL\fP   '\\x1B[33m'"
.br
.ti -1c
.RI "#define \fBBLU\fP   '\\x1B[34m'"
.br
.ti -1c
.RI "#define \fBMAG\fP   '\\x1B[35m'"
.br
.ti -1c
.RI "#define \fBCYN\fP   '\\x1B[36m'"
.br
.ti -1c
.RI "#define \fBWHT\fP   '\\x1B[37m'"
.br
.ti -1c
.RI "#define \fBRESET\fP   '\\x1B[0m'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definicion de tipos e includes comunes utilizados por los distintos modulos\&. 


.PP
\fBAuthor:\fP
.RS 4
Alfonso Sebares 
.PP
Beatriz de Pablo 
.PP
Celia Mateos 
.RE
.PP
\fBDate:\fP
.RS 4
13/02/17 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define BLU   '\\x1B[34m'"

.SS "#define CYN   '\\x1B[36m'"

.SS "#define ERR   -1"

.SS "#define GRN   '\\x1B[32m'"

.SS "#define MAG   '\\x1B[35m'"

.SS "#define MAX_IRC_COMMAND   1000 /*https://www\&.alien\&.net\&.au/irc/irc2numerics\&.html*/"

.SS "#define MAXDATA   1024"

.SS "#define OK   0"

.SS "#define RED   '\\x1B[31m'"

.SS "#define RESET   '\\x1B[0m'"

.SS "#define WHT   '\\x1B[37m'"

.SS "#define YEL   '\\x1B[33m'"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
