.TH "unpipe" 3 "Mon May 8 2017" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
unpipe \- unpipe 
Funcion para dividir en comandos la cadena 'message' Tiene implementada una logica de concatenacion de trozos de comandos de cara a cuando se lee el tamaño maximo del buffer de lectura en el socket y se corta un comando en 2 lecturas\&. 
.PP
.PP
.nf
#include "xchat2\&.h"

void unpipe(char* message, int MAXDATA_flag);
.fi
.PP
.PP
\fBParameters:\fP
.RS 4
\fImassage\fP Mensaje recibido para procesar 
.br
\fIMAXDATA_flag\fP Flag que viene activada si se alcanzó el máximo de Bytes leidos por el buffer del socket
.RE
.PP
\fBReturns:\fP
.RS 4
Void
.RE
.PP
\fBAuthor:\fP
.RS 4
Celia Mateos de Miguel (cel.mateos@estudiante.uam.es) Beatriz de Pablo Garcia (beatriz.depablo@estudiante.uam.es) Alfonso Sebares Mecha (alfonso.sebares@estudiante.uam.es)
.RE
.PP
\fBDate:\fP
.RS 4
13 de febrero de 2017
.RE
.PP
.PP
 
