.TH "val" 3 "Mon May 8 2017" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
val \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <logger\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBint_val\fP"
.br
.ti -1c
.RI "long \fBllong_val\fP"
.br
.ti -1c
.RI "char * \fBstr\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int val::int_val"

.SS "long val::llong_val"

.SS "char* val::str"


.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
